### PR TITLE
Fix for the hash error on song download (issue 121)

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
I've rebuilded the app in local and the "hash error" is gone.

It's easy to test with this music for example, open a browser and use this url : 

http://www.beatsaver.com/api/download/key/7d51
http://beatsaver.com/api/download/key/7d51

Error on first link : "404 Site www.beatsaver.com is not served on this interface"

Good job @cinnapanda you found the problem :)

### CODE REVIEW

**Comment by M0NsTeRRR** [comment]
Tested with https, also works

https://www.beatsaver.com/api/download/key/7d51
https://beatsaver.com/api/download/key/7d51

**Comment by bluedot74** [comment]
This works for me!

**Comment by cinnapanda** [comment]
Thank you kindly! And no prob!

**Comment by ajaxvcu** [comment]
Does this need more than an `npm install` to build. I'm not a Windows guy :(

**Comment by M0NsTeRRR** [comment]
@ajaxvcu `npm install && npm run publish` will build and create you an .exe in `dist/` folder

**Comment by BladesOni** [comment]
Hey, didn't really understand what to do to fix. can I get some help

**Comment by ajaxvcu** [comment]
@MONsTeRRR I get compilation errors with `npm install` Any special libraries/tools I need to install on Windows, besides Node?

**Comment by StarGazer1258** [comment]
`npm install && npm run build` will suffice to build binaries, `npm run publish` is for publishing releases to GitHub.

You may also have you run `npm install --global --production windows-build-tools` first for some dependencies to build.

**Comment by M0NsTeRRR** [comment]
I understood the opposite concerning the `www` fixed

**Comment by M0NsTeRRR** [comment]
IDE settings problem ^^

**Comment by csilla-vilagos** [comment]
PLS someone explain to me how to fix this issue? My BeatDrop is up to date but I still get the error...

**Comment by ajaxvcu** [comment]
The latest changes worked for me. Although, I had to remove the `package-lock.json` file to get it to build with the latest versions of `node` and `npm`.

**Comment by StarGazer1258** [comment]
Typically, I would avoid merging directly to master; however, since this is such a minor fix, I will allow it.

**Pull request merged**
