### PR TITLE
Fix for the hash error on song download (issue 132)

### PR DESCRIPTION
**Pull request by bluedot74**
Should fix this issue: https://github.com/StarGazer1258/BeatDrop/issues/132

### CODE REVIEW

**Comment by StarGazer1258** [comment]
Sorry, I haven't had much time recently to spend on BeatDrop. Has it been confirmed or can you confirm that this is reason downloads are failing?

**Comment by bluedot74** [comment]
> Sorry, I haven't had much time recently to spend on BeatDrop. Has it been confirmed or can you confirm that this is reason downloads are failing?

Unfortunately I can't be sure. I got the electron app running locally and tested it, but all the download actions fail with Error 525 from Cloudflare. I think this is because the localhost is http and I don't have a local cert. So even if I fix the https on those two actions I'm still making a request from http://localhost. 

But if I'm being honest I'm making a lot of assumptions, this is the first Electron app I've messed with.

**Comment by M0NsTeRRR** [comment]
check #144 
I've tested with your fix and it doesn't work for me.

**Comment by bluedot74** [comment]
> check #144
> I've tested with your fix and it doesn't work for me.

Yup I agree, finally got my local working enough to test. Adding just https doesn't fix.

**Pull request closed without merging**
